trigger:
- main

# reference a shared repo that stores pipeline templates
resources:
  repositories:
    - repository: cicd-templates              # Alias used locally
      type: github
      name: kendedc/test-cicd-template        # Example repo name
      ref: refs/heads/main                    # Branch to pull from
      endpoint: kendedc

pool:
  vmImage: ubuntu-latest

parameters:
  - name: nodeVersion
    type: string
    default: '18.x'
  - name: isPrint
    type: boolean
    default: true

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: InstallNode
    displayName: 'Install Node Job'
    steps:
    - template: install-node.yml@cicd-templates
      parameters:
        nodeVersion: ${{ parameters.nodeVersion }}
  - job: Build
    displayName: 'Build Job'
    dependsOn: InstallNode
    steps:
    - template: npm-steps.yml@cicd-templates

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Test Job'
    steps:
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
      displayName: 'Publish Test Results'

- stage: Print
  displayName: 'Print Stage'
  jobs:
  - job: Print
    displayName: 'Print Job'
    script: |
      echo "${{ variables['Build.SourceBranch'] }}"
      echo "${{ variables['Build.SourceVersion'] }}"
      echo "${{ variables['Build.Reason'] }}"