# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

# reference a shared repo that stores pipeline templates
resources:
  repositories:
    - repository: cicd-templates              # Alias used locally
      type: github
      name: kendedc/test-cicd-template        # Example repo name
      ref: refs/heads/main                    # Branch to pull from

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- template: npm-steps.yml@cicd-templates

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'npm install and build'
