trigger:
- main

# reference a shared repo that stores pipeline templates
resources:
  repositories:
    - repository: cicd-templates              # Alias used locally
      type: github
      name: kendedc/test-cicd-template        # Example repo name
      ref: refs/heads/main                    # Branch to pull from
      endpoint: kendedc

pool:
  vmImage: ubuntu-latest

parameters:
  - name: nodeVersion
    type: string
    default: '18.x'
  - name: isPrint
    type: boolean
    default: false

steps:
- template: install-node.yml@cicd-templates
  parameters:
    nodeVersion: ${{ parameters.nodeVersion }}

- template: npm-steps.yml@cicd-templates

- ${{ if eq(parameters.isPrint, true) }}:
  - template: print.yml@cicd-templates
    parameters:
      isPrint: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'npm install and build'
